pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = uri('https://maven.fabricmc.net/') }
        maven { url = uri('https://repo.papermc.io/repository/maven-public/') }
    }
}

rootProject.name = 'AntiFly'
include 'common', 'paper', 'fabric_12111', 'fabric_2612', 'fabric_262', 'fabric_263'
