plugins {
    id 'net.fabricmc.fabric-loom' version '1.17.14'
}

base {
    archivesName = 'AntiFly-fabric-26.2'
}

def commonProject = project(':common')

dependencies {
    minecraft "com.mojang:minecraft:${fabric262_minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric262_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric262_api_version}"
    implementation commonProject
}

tasks.processResources {
    inputs.property 'version', project.version
    inputs.property 'minecraft_version', project.fabric262_minecraft_version
    inputs.property 'loader_version', project.fabric262_loader_version
    filteringCharset = 'UTF-8'
    filesMatching('fabric.mod.json') {
        expand(
            version: project.version,
            fabric_minecraft_version: project.fabric262_minecraft_version,
            fabric_loader_version: project.fabric262_loader_version
        )
    }
}

tasks.named('jar').configure {
    dependsOn(commonProject.tasks.named('classes'))
    from(commonProject.sourceSets.main.output)
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
}

loom {
    enableModProvidedJavadoc.set(false)
    interfaceInjection {
        enableDependencyInterfaceInjection.set(false)
    }
}
