name: AntiFly
version: ${version}
main: com.antifly.paper.AntiFlyPlugin
api-version: '1.21'
commands:
  antifly:
    description: AntiFly administration
    usage: /antifly <help|enable|disable|status|exempt|unexempt|set|reset>
    permission: antifly.admin
permissions:
  antifly.admin:
    description: Allows managing AntiFly
    default: op
